"""added cards model

Revision ID: 08e9b172d775
Revises: f4aae4cbcfdc
Create Date: 2024-08-21 00:32:55.035837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08e9b172d775'
down_revision: Union[str, None] = 'f4aae4cbcfdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        'virtual_cards',
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('user_id', sa.Integer, sa.ForeignKey('users.id')),
        sa.Column('description', sa.String, nullable=False),
        sa.Column('card_type', sa.String, nullable=False),
        sa.Column('card_style', sa.String, nullable=False),
        sa.Column('top_up_amount', sa.Float, nullable=False),
        sa.Column('currency', sa.String, nullable=False),
    )



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
