"""Added new fields to Profile model

Revision ID: 67d472dea84b
Revises: 0b4d683968b6
Create Date: 2024-08-19 09:12:21.816399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '67d472dea84b'
down_revision: Union[str, None] = '0b4d683968b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('billing_plans')
    op.add_column('profiles', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('last_name', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('email_address', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('student_id', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('date_of_birth', sa.Date(), nullable=True))
    op.add_column('profiles', sa.Column('additional_information', sa.Text(), nullable=True))
    op.add_column('profiles', sa.Column('institution_information', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('payment_information', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('country_paying_from', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('discount_code', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('payment_for', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('payment_by', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('transaction_summary', sa.Text(), nullable=True))
    op.drop_column('profiles', 'job_title')
    op.drop_column('profiles', 'pronouns')
    op.drop_column('profiles', 'department')
    op.drop_column('profiles', 'avatar_url')
    op.drop_column('profiles', 'phone_number')
    op.drop_column('profiles', 'bio')
    op.drop_column('profiles', 'username')
    op.drop_column('profiles', 'recovery_email')
    op.drop_column('profiles', 'social')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('social', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('profiles', sa.Column('recovery_email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('profiles', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('profiles', sa.Column('bio', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('profiles', sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('profiles', sa.Column('avatar_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('profiles', sa.Column('department', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('profiles', sa.Column('pronouns', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('profiles', sa.Column('job_title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('profiles', 'transaction_summary')
    op.drop_column('profiles', 'payment_by')
    op.drop_column('profiles', 'payment_for')
    op.drop_column('profiles', 'discount_code')
    op.drop_column('profiles', 'country_paying_from')
    op.drop_column('profiles', 'payment_information')
    op.drop_column('profiles', 'institution_information')
    op.drop_column('profiles', 'additional_information')
    op.drop_column('profiles', 'date_of_birth')
    op.drop_column('profiles', 'student_id')
    op.drop_column('profiles', 'email_address')
    op.drop_column('profiles', 'last_name')
    op.drop_column('profiles', 'first_name')
    op.create_table('billing_plans',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('institution_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('duration', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('features', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='billing_plans_pkey')
    )
    # ### end Alembic commands ###
