"""Add address column to institutions table

Revision ID: 6b30ceb9b047
Revises: d3bd8e0090c9
Create Date: 2024-08-09 14:24:56.395278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b30ceb9b047'
down_revision: Union[str, None] = 'd3bd8e0090c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('institutions', sa.Column('address', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('institutions', 'address')
    # ### end Alembic commands ###
