"""initial migration

Revision ID: 6e8aa2b4ec7c
Revises: 6b30ceb9b047
Create Date: 2024-08-10 15:32:00.483564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e8aa2b4ec7c'
down_revision: Union[str, None] = '6b30ceb9b047'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
