"""Added new fields to Profile model

Revision ID: 7d9cee3906ec
Revises: 67d472dea84b
Create Date: 2024-08-19 10:10:29.542827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d9cee3906ec'
down_revision: Union[str, None] = '67d472dea84b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'phone_number')
    # ### end Alembic commands ###
