"""initial migration

Revision ID: c72f18e3426b
Revises: 6daad3f45be8
Create Date: 2024-08-03 21:36:51.325411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c72f18e3426b'
down_revision: Union[str, None] = '6daad3f45be8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('contacts_institution_id_fkey', 'contacts', type_='foreignkey')
    op.drop_constraint('contacts_user_id_fkey', 'contacts', type_='foreignkey')
    op.drop_column('contacts', 'user_id')
    op.drop_column('contacts', 'institution_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('institution_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('contacts', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key('contacts_user_id_fkey', 'contacts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('contacts_institution_id_fkey', 'contacts', 'institutions', ['institution_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
