"""Initial migration

Revision ID: e55de9ad0060
Revises: 7f8371dc902a
Create Date: 2024-07-10 23:49:42.607460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e55de9ad0060'
down_revision: Union[str, None] = '7f8371dc902a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('institutions', sa.Column('school_name', sa.String(), nullable=True))
    op.add_column('institutions', sa.Column('country_name', sa.String(), nullable=True))
    op.add_column('institutions', sa.Column('payment_type', sa.String(), nullable=True))
    op.add_column('institutions', sa.Column('contact_email', sa.String(), nullable=True))
    op.drop_index('ix_institutions_contactEmail', table_name='institutions')
    op.drop_index('ix_institutions_countryName', table_name='institutions')
    op.drop_index('ix_institutions_paymentType', table_name='institutions')
    op.drop_index('ix_institutions_schoolName', table_name='institutions')
    op.create_index(op.f('ix_institutions_contact_email'), 'institutions', ['contact_email'], unique=False)
    op.create_index(op.f('ix_institutions_country_name'), 'institutions', ['country_name'], unique=False)
    op.create_index(op.f('ix_institutions_payment_type'), 'institutions', ['payment_type'], unique=False)
    op.create_index(op.f('ix_institutions_school_name'), 'institutions', ['school_name'], unique=False)
    op.drop_column('institutions', 'contactEmail')
    op.drop_column('institutions', 'schoolName')
    op.drop_column('institutions', 'countryName')
    op.drop_column('institutions', 'paymentType')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('institutions', sa.Column('paymentType', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('institutions', sa.Column('countryName', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('institutions', sa.Column('schoolName', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('institutions', sa.Column('contactEmail', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_institutions_school_name'), table_name='institutions')
    op.drop_index(op.f('ix_institutions_payment_type'), table_name='institutions')
    op.drop_index(op.f('ix_institutions_country_name'), table_name='institutions')
    op.drop_index(op.f('ix_institutions_contact_email'), table_name='institutions')
    op.create_index('ix_institutions_schoolName', 'institutions', ['schoolName'], unique=False)
    op.create_index('ix_institutions_paymentType', 'institutions', ['paymentType'], unique=False)
    op.create_index('ix_institutions_countryName', 'institutions', ['countryName'], unique=False)
    op.create_index('ix_institutions_contactEmail', 'institutions', ['contactEmail'], unique=False)
    op.drop_column('institutions', 'contact_email')
    op.drop_column('institutions', 'payment_type')
    op.drop_column('institutions', 'country_name')
    op.drop_column('institutions', 'school_name')
    # ### end Alembic commands ###
