"""added cards model

Revision ID: f6d945cc6d26
Revises: 08e9b172d775
Create Date: 2024-08-21 09:59:40.073304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6d945cc6d26'
down_revision: Union[str, None] = '08e9b172d775'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        'virtual_cards',
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('user_id', sa.String, sa.ForeignKey('users.id')),  # Change this to String
        sa.Column('description', sa.String, nullable=False),
        sa.Column('card_type', sa.String, nullable=False),
        sa.Column('card_style', sa.String, nullable=False),
        sa.Column('top_up_amount', sa.Float, nullable=False),
        sa.Column('currency', sa.String, nullable=False),
    )




def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
